=== EOSC-CZ/CCMM/ccmm-v01.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:ccmm="https://www.techlib.cz/ontologies/czech-core-metadata-model/"
    targetNamespace="https://www.techlib.cz/ontologies/czech-core-metadata-model/"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xs:include schemaLocation="include/identifierScheme.xsd" />
    <xs:include schemaLocation="include/mediaTypeScheme.xsd" />
    <xs:include schemaLocation="include/checksumAlgorithmScheme.xsd" />


    <xs:element name="dataset">
        <xs:complexType>
            <xs:all>
                <xs:element name="creators">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="creator" type="ccmm:AuthorityType" minOccurs="1"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="contributors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="contributor" type="ccmm:ContributorType" minOccurs="0"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="publishers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="publisher" type="ccmm:OrganizationType" minOccurs="1"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="identifier" type="ccmm:IdentifierType" minOccurs="1" maxOccurs="1" />

                <xs:element name="alternateIdentifiers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alternateIdentifier" type="ccmm:IdentifierType"
                                minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="title" type="ccmm:langString" minOccurs="1" maxOccurs="1" />

                <xs:element name="alternateTitles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alternateTitle" type="ccmm:langString" minOccurs="0"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="resourceType" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="abstract" type="ccmm:langString" minOccurs="1" maxOccurs="1" />

                <xs:element name="funding">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="award" type="ccmm:AwardType" minOccurs="0"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="subjects">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subject" type="ccmm:SubjectType" minOccurs="0"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="termsOfUseList">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="accessRights" type="ccmm:RightsType" minOccurs="1"
                                maxOccurs="1" />
                            <xs:element name="license" type="ccmm:RightsType" minOccurs="0"
                                maxOccurs="1" />
                            <xs:element name="description" type="ccmm:langString" minOccurs="0"
                                maxOccurs="1" />
                            <xs:element name="otherRights" type="ccmm:OtherRightsType" minOccurs="0"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="timeReferences">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="publicationYear" type="xs:gYear" minOccurs="1"
                                maxOccurs="1" />
                            <xs:element name="timeReference" type="ccmm:TimeReferenceType" minOccurs="0"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="relatedResources">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="relatedResource" type="ccmm:RelatedResourceType"
                                minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="distributions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="distribution" type="ccmm:DistributionType"
                                minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="geolocations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="geolocation" type="ccmm:GeolocationType" minOccurs="0"
                                maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="AuthorityType" abstract="true">
        <xs:sequence>
            <xs:element name="identifier" type="ccmm:IdentifierType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="contactDetails" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="contactDetail" type="ccmm:ContactDetailType"
                                minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PersonType">
        <xs:complexContent>
            <xs:extension base="ccmm:AuthorityType">
                <xs:sequence>
                    <xs:element name="givenName" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="familyName" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="affiliation" type="ccmm:OrganizationType" minOccurs="0"
                        maxOccurs="unbounded" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="OrganizationType">
        <xs:complexContent>
            <xs:extension base="ccmm:AuthorityType">
                <xs:sequence>
                    <xs:element name="organizationName" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="alternateName" type="xs:string" minOccurs="0"
                        maxOccurs="unbounded" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="ContributorType">
        <xs:sequence>
            <xs:element name="identifier" type="ccmm:IdentifierType" minOccurs="0"
                maxOccurs="unbounded" />
            <xs:choice>
                <xs:sequence>
                    <xs:element name="givenName" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="familyName" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="affiliation" type="ccmm:OrganizationType" minOccurs="0"
                        maxOccurs="unbounded" />
                </xs:sequence>
                <xs:sequence>
                    <xs:element name="organizationName" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="alternateName" type="xs:string" minOccurs="0"
                        maxOccurs="unbounded" />
                </xs:sequence>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="role" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="ContactDetailType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="contactType" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="IdentifierType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="identifierScheme" type="ccmm:identifierScheme" use="required" />
                <xs:attribute name="schemeURI" type="xs:anyURI" use="optional" />
                <xs:attribute name="valueURI" type="xs:anyURI" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="langString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:language" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="AwardType">
        <xs:sequence>
            <xs:element name="localIdentifier" type="ccmm:IdentifierType" minOccurs="1"
                maxOccurs="1" />
            <xs:element name="alternateIdentifier" type="ccmm:IdentifierType" minOccurs="0"
                maxOccurs="unbounded" />
            <xs:element name="awardTitle" type="ccmm:langString" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="fundingProgram" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="funder" type="ccmm:OrganizationType" minOccurs="1"
                maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SubjectType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="subjectScheme" use="optional" />
                <xs:attribute name="schemeURI" type="xs:anyURI" use="optional" />
                <xs:attribute name="valueURI" type="xs:anyURI" use="optional" />
                <xs:attribute name="classificationCode" type="xs:anyURI" use="optional" />
                <xs:attribute name="lang" type="xs:language" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="RightsType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="rightsURI" type="xs:anyURI" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="OtherRightsType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="rightsType" type="xs:string" use="required" />
                <xs:attribute name="rightsURI" type="xs:anyURI" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:complexType name="RelatedResourceType">
        <xs:sequence>
            <xs:element name="identifier" type="ccmm:IdentifierType" minOccurs="1"
                maxOccurs="unbounded" />
            <xs:element name="title" type="ccmm:langString" minOccurs="1" maxOccurs="1" />
            <xs:element name="resourceType" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="creators" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="creator" type="ccmm:AuthorityType" minOccurs="1"
                            maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="contributors" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="contributor" type="ccmm:ContributorType" minOccurs="0"
                            maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="publishers" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="publisher" type="ccmm:OrganizationType" minOccurs="1"
                            maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="timeReferences" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="publicationYear" type="xs:gYear" minOccurs="1"
                            maxOccurs="1" />
                        <xs:element name="timeReference" type="ccmm:TimeReferenceType" minOccurs="0"
                            maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="relationType" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="DistributionType" abstract="true">
        <xs:sequence>
            <xs:element name="distributionName" type="xs:string" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="FileType">
        <xs:complexContent>
            <xs:extension base="ccmm:DistributionType">
                <xs:sequence>
                    <xs:element name="downloadURL" type="xs:anyURI" minOccurs="1" maxOccurs="1" />
                    <xs:element name="mediaType" type="ccmm:mediaTypeScheme" minOccurs="1"
                        maxOccurs="1" />
                    <xs:element name="innerFormat" type="ccmm:mediaTypeScheme" minOccurs="0"
                        maxOccurs="unbounded" />
                    <xs:element name="checksum" type="ccmm:ChecksumType" minOccurs="1" maxOccurs="1" />
                    <xs:element name="byteSize" type="xs:positiveInteger" minOccurs="1"
                        maxOccurs="1" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="DataServiceType">
        <xs:complexContent>
            <xs:extension base="ccmm:DistributionType">
                <xs:sequence>
                    <xs:element name="endpointURL" type="xs:anyURI" minOccurs="1" maxOccurs="1" />
                    <xs:element name="description" type="ccmm:langString" minOccurs="0"
                        maxOccurs="1" />

                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ChecksumType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="algorithm" type="ccmm:checksumAlgorithmScheme" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="GeolocationType">
        <xs:choice>
            <xs:element name="geolocationName" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="geolocationPoint" type="ccmm:PointType" minOccurs="0" maxOccurs="1" />
            <xs:element name="geolocationBox" type="ccmm:BoxType" minOccurs="0" maxOccurs="1" />
        </xs:choice>
        <xs:attribute name="relationType" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="PointType">
        <xs:all>
            <xs:element name="pointLongitude" type="ccmm:LongitudeType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="pointLatitude" type="ccmm:LatitudeType" minOccurs="1" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="BoxType">
        <xs:all>
            <xs:element name="westBoundLongitude" type="ccmm:LongitudeType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="eastBoundLongitude" type="ccmm:LongitudeType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="southBoundLatitude" type="ccmm:LatitudeType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="northBoundLatitude" type="ccmm:LatitudeType" minOccurs="1" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="LongitudeType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="-180" />
            <xs:maxInclusive value="180" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="LatitudeType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="-90" />
            <xs:maxInclusive value="90" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="genDate">
        <xs:union memberTypes="xs:dateTime xs:date xs:gYearMonth xs:gYear"/>
    </xs:simpleType>


    <xs:complexType name="TimeReferenceType">
        <xs:sequence>
            <xs:choice>
                <xs:element name="date" type="ccmm:genDate"/>
                <xs:element name="dateRange" type="ccmm:DateRangeType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="timeReferenceType" type="xs:string" use="required"/>
    </xs:complexType>

   
    <xs:complexType name="DateRangeType">
        <xs:sequence>
            <xs:element name="startDate" type="ccmm:genDate" />
            <xs:element name="endDate" type="ccmm:genDate" />
        </xs:sequence>
    </xs:complexType>

 <!-- XXX  -->

</xs:schema>

=== EOSC-CZ/CCMM/ccmm-example1.xml
<ccmm:dataset 
    xmlns:ccmm="https://www.techlib.cz/ontologies/czech-core-metadata-model/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.techlib.cz/ontologies/czech-core-metadata-model/ ccmm-v01.xsd">

    <ccmm:identifier identifierScheme="DOI">10.5281/zenodo.14001488</ccmm:identifier>
    <ccmm:alternateIdentifiers>
        <ccmm:alternateIdentifier identifierScheme="handle">20.500/1257</ccmm:alternateIdentifier>
        <ccmm:alternateIdentifier identifierScheme="URL">https://zenodo.org/records/14001488</ccmm:alternateIdentifier>
        <ccmm:alternateIdentifier identifierScheme="oai">oai:zenodo.org:14001488</ccmm:alternateIdentifier>
    </ccmm:alternateIdentifiers>

    <ccmm:title lang="en"> Very important dataset </ccmm:title>
    <ccmm:alternateTitles>
        <ccmm:alternateTitle lang="cs"> Velmi dulezita datova sada </ccmm:alternateTitle>
    </ccmm:alternateTitles>

    <ccmm:resourceType>lab notebook</ccmm:resourceType>
    <ccmm:abstract lang="en">very and very important</ccmm:abstract>

    <ccmm:creators>
        <ccmm:creator xsi:type="ccmm:PersonType">
            <ccmm:identifier identifierScheme="ORCID">0000-0001-5727-2427</ccmm:identifier>
            <ccmm:givenName>Sofia</ccmm:givenName>
            <ccmm:familyName>Garcia</ccmm:familyName>
            <ccmm:affiliation>
                <ccmm:identifier identifierScheme="ROR" valueURI="https://ror.org/03efmqc40">03efmqc40</ccmm:identifier>
                <ccmm:organizationName>Arizona State University</ccmm:organizationName>
                <ccmm:alternateName>Arizona State Uni</ccmm:alternateName>
                <ccmm:alternateName>ASU</ccmm:alternateName>
            </ccmm:affiliation>
        </ccmm:creator>

        <ccmm:creator xsi:type="ccmm:OrganizationType">
            <ccmm:identifier identifierScheme="ROR" schemeURI="https://ror.org/">03yrm5c26</ccmm:identifier>
            <ccmm:organizationName>California Digital Library</ccmm:organizationName>
        </ccmm:creator>
    </ccmm:creators>

    <ccmm:contributors>
        <ccmm:contributor role="DataCollector">
            <ccmm:identifier identifierScheme="ORCID">0000-0002-1825-0097</ccmm:identifier>
            <ccmm:givenName>Jordan</ccmm:givenName>
            <ccmm:familyName>Lee</ccmm:familyName>
            <ccmm:affiliation>
                <ccmm:identifier identifierScheme="ROR">03yrm5c26</ccmm:identifier>
                <ccmm:organizationName>University of California</ccmm:organizationName>
            </ccmm:affiliation>
        </ccmm:contributor>
    </ccmm:contributors>

    <ccmm:publishers>
        <ccmm:publisher>
            <ccmm:identifier identifierScheme="URL">https://zenodo.org</ccmm:identifier>
            <ccmm:organizationName>zenodo</ccmm:organizationName>
        </ccmm:publisher>
    </ccmm:publishers>

    <ccmm:funding>
        <ccmm:award>
            <ccmm:localIdentifier identifierScheme="cordis" valueURI="https://cordis.europa.eu/project/id/874457">894457</ccmm:localIdentifier>
            <ccmm:alternateIdentifier identifierScheme="DOI">10.3030/874465</ccmm:alternateIdentifier>
            <ccmm:alternateIdentifier identifierScheme="URL">https://app.dimensions.ai/details/grant/grant.8586176</ccmm:alternateIdentifier>
            <ccmm:awardTitle>Motion Powered 3D Printed Self-Healable Energy Storage</ccmm:awardTitle>
            <ccmm:fundingProgram>H2020</ccmm:fundingProgram>
            <ccmm:funder>
                <ccmm:organizationName>European Commission</ccmm:organizationName>
            </ccmm:funder>
        </ccmm:award>

        <ccmm:award>
            <ccmm:localIdentifier identifierScheme="isvavai">GA 456/2016</ccmm:localIdentifier>
            <ccmm:awardTitle lang="en">Supa Dupa Energy Storage</ccmm:awardTitle>
            <ccmm:funder>
                <ccmm:organizationName>Grantova agentura CR</ccmm:organizationName>
                <ccmm:alternateName>GACR</ccmm:alternateName>
            </ccmm:funder>
        </ccmm:award>

    </ccmm:funding>

    <ccmm:subjects>
        <ccmm:subject subjectScheme="Fields of Science and Technology (FOS)" schemeURI="http://www.oecd.org/science/inno/38235147.pdf">FOS: Earth and related environmental sciences</ccmm:subject>
        <ccmm:subject subjectScheme="Wikidata" schemeURI="https://www.wikidata.org/wiki" valueURI="https://www.wikidata.org/wiki/Q11466">temperature</ccmm:subject>
        <ccmm:subject subjectScheme="Art and Architecture Thesaurus" schemeURI="http://vocab.getty.edu/aat" valueURI="http://vocab.getty.edu/aat/300192097">relative humidity</ccmm:subject>
        <ccmm:subject subjectScheme="Wikidata" schemeURI="https://www.wikidata.org/wiki" valueURI="https://www.wikidata.org/wiki/Q194411">illuminance</ccmm:subject>
        <ccmm:subject subjectScheme="Art and Architecture Thesaurus" schemeURI="http://vocab.getty.edu/aat" valueURI="http://vocab.getty.edu/aat/300379432">moisture content</ccmm:subject>
        <ccmm:subject subjectScheme="FAST" schemeURI="http://id.worldcat.org/fast" valueURI="http://id.worldcat.org/fast/913214">Environmental monitoring</ccmm:subject>
        <ccmm:subject lang="en">temperature</ccmm:subject>
        <ccmm:subject lang="cs">teplota</ccmm:subject>
        
    </ccmm:subjects>

    <ccmm:termsOfUse>
        <ccmm:accessRights rightsURI="http://purl.org/coar/access_right/c_16ec">restricted access</ccmm:accessRights>
        <ccmm:rights rightsType="license" rightsURI="https://creativecommons.org/licenses/by-nc/4.0/">CC-BY-4.0</ccmm:rights>
        <ccmm:rights rightsType="personalData" rightsURI="https://data.gov.cz/podm%C3%ADnky-u%C5%BEit%C3%AD/nen%C3%AD-specifikov%C3%A1no-zda-obsahuje-osobn%C3%AD-%C3%BAdaje/">Není specifikováno, zda obsahuje osobní údaje.</ccmm:rights>
    </ccmm:termsOfUse>

    <ccmm:timeReferences>
        <ccmm:publicationYear>2022</ccmm:publicationYear>
        <ccmm:date dateType="collected">2010/2020</ccmm:date>
        <ccmm:date dateType="timeCoverage">2010/2020</ccmm:date>
    </ccmm:timeReferences>
</ccmm:dataset>
